// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2SH8Mhd-La8uAu2NsK-woh9E6RCzomlQ',
    appId: '1:1045173371133:web:f39bf595dba3ef5f447e94',
    messagingSenderId: '1045173371133',
    projectId: 'tubesabp-8173d',
    authDomain: 'tubesabp-8173d.firebaseapp.com',
    storageBucket: 'tubesabp-8173d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFgiWhsJt2Qoi2MAeK2xQ_bc_jBvMPv40',
    appId: '1:1045173371133:android:ea2e1968f8fed8a8447e94',
    messagingSenderId: '1045173371133',
    projectId: 'tubesabp-8173d',
    storageBucket: 'tubesabp-8173d.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2SH8Mhd-La8uAu2NsK-woh9E6RCzomlQ',
    appId: '1:1045173371133:web:fcba93b6a715339e447e94',
    messagingSenderId: '1045173371133',
    projectId: 'tubesabp-8173d',
    authDomain: 'tubesabp-8173d.firebaseapp.com',
    storageBucket: 'tubesabp-8173d.appspot.com',
  );

}